mindmup:
  original_file: your_original_map.mup

jira:
  weburl: https://url_you_use_to_browse_Jira/browse
  rest_search_url: https://the_url_to_your_jira_server/search?jql=a_url_encoded_Jql_search_string

# Idea Formatter examples below:
#   Right now: Labels, status, sprints and versions can be coded in different colors 
#   Same key can be used multiple times 
#   Order of keys matter. First match is used
idea_formatter: 

-
  key: sprints
  value: Titan 2014 v. 45-47
  color: '#BBA0FF'
-
  key: labels
  value: customer_accepted
  color: '#008000'
-
  key: status
  value: Closed
  color: '#FFFF00'
- 
  key: versions
  value: '1.0'
  color: '#FF6666'


