mindmup:
  original_file: your_original_map.mup

jira:
  weburl: https://url_you_use_to_browse_Jira/browse
  rest_search_url: https://the_url_to_your_jira_server/search?jql=a_url_encoded_Jql_search_string

  config:
    sprint: customfield_10270      # Sprint is a customfield in JIRA, change it to ID of custom field used in your installation
    storypoints: customfield_10043 # Storypoints is a customfield in JIRA, change it to ID of custom field used in your installation 

# Idea Formatter examples below:
#   The following can be can be coded in different colors: 
#   * labels
#   * status
#   * sprints
#   * versions 
#   Same key can be used multiple times 
#   Order of keys matter. First match is used
idea_formatter: 
-
  key: sprints
  value: Titan 2014 v. 45-47
  color: '#BBA0FF'
-
  key: labels
  value: customer_accepted
  color: '#008000'
-
  key: status
  value: Closed
  color: '#FFFF00'
- 
  key: versions
  value: '1.0'
  color: '#FF6666'


