mindmup:
  original_file: aurff_new2.mup

jira:
  weburl: urlYouUseToBrowseJira/browse
  rest_search_url: theUrlToYourJiraServer/search?jql=aUrlEncodedJqlString
  username: yourUsername
  password: yourPassword

idea_formatter: #Examples below. 
#Right now labels, status and versions can be coded in different colors (Order matters. First match is used)
-
  key: labels
  value: customer_accepted
  color: '#008000'
-
  key: status
  value: Closed
  color: '#FFFF00'
- 
  key: versions
  value: '1.0'
  color: '#FF6666'


